begin;

create table if not exists public.greenhouse_units (
  id bigint generated by default as identity primary key,
  cbs_unit_id bigint references public.cbs_units(id) on delete set null,
  producer_id bigint references public.kobuks_producers(id) on delete set null,
  unit_no text unique not null,
  registration_no text,
  greenhouse_area numeric,
  parcel_polygon jsonb,
  greenhouse_polygon jsonb,
  latitude numeric,
  longitude numeric,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inspection_history (
  id bigint generated by default as identity primary key,
  greenhouse_unit_id bigint references public.greenhouse_units(id) on delete set null,
  producer_id bigint references public.kobuks_producers(id) on delete set null,
  inspector_user_id uuid references public.profiles(id) on delete set null,
  task_id bigint references public.tasks(id) on delete set null,
  unit_no text,
  status text not null default 'Sahada',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  notes text,
  result text,
  latitude numeric,
  longitude numeric,
  created_at timestamptz not null default now()
);

alter table public.cbs_units
  add column if not exists tkgm_parcel_id text,
  add column if not exists city text,
  add column if not exists district text,
  add column if not exists village text,
  add column if not exists unit_no text,
  add column if not exists greenhouse_polygon jsonb,
  add column if not exists latitude numeric,
  add column if not exists longitude numeric,
  add column if not exists greenhouse_area numeric,
  add column if not exists created_by uuid,
  add column if not exists updated_by uuid,
  add column if not exists source text not null default 'cbs',
  add column if not exists source_accuracy text,
  add column if not exists source_srid integer,
  add column if not exists source_updated_at timestamptz,
  add column if not exists source_geometry jsonb,
  add column if not exists geometry_hash text,
  add column if not exists source_payload jsonb,
  add column if not exists ingested_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.greenhouse_units
  add column if not exists parcel_polygon jsonb;

alter table public.tasks
  add column if not exists parcel_polygon jsonb,
  add column if not exists greenhouse_polygon jsonb,
  add column if not exists cbs_unit_id bigint references public.cbs_units(id) on delete set null,
  add column if not exists greenhouse_unit_id bigint references public.greenhouse_units(id) on delete set null,
  add column if not exists inspection_id bigint references public.inspection_history(id) on delete set null,
  add column if not exists workflow_type text;

create unique index if not exists cbs_units_tkgm_parcel_id_idx
  on public.cbs_units(tkgm_parcel_id)
  where tkgm_parcel_id is not null;
create index if not exists cbs_units_source_idx on public.cbs_units(source);

create or replace function public.can_write_cbs()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'manager', 'inspector')
  );
$$;

revoke all on function public.can_write_cbs() from public;
grant execute on function public.can_write_cbs() to authenticated;

alter table public.cbs_units enable row level security;
alter table public.greenhouse_units enable row level security;
alter table public.inspection_history enable row level security;

grant select, insert, update on table public.cbs_units to authenticated;
grant select, insert, update on table public.greenhouse_units to authenticated;
grant select, insert, update on table public.inspection_history to authenticated;
grant usage, select on sequence public.greenhouse_units_id_seq to authenticated;
grant usage, select on sequence public.inspection_history_id_seq to authenticated;
do $$
declare
  cbs_id_sequence text;
begin
  cbs_id_sequence := pg_get_serial_sequence('public.cbs_units', 'id');
  if cbs_id_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', cbs_id_sequence);
  end if;
end;
$$;

drop policy if exists "authenticated can read cbs units" on public.cbs_units;
create policy "authenticated can read cbs units"
on public.cbs_units for select
to authenticated
using (true);

drop policy if exists "cbs writers can insert cbs units" on public.cbs_units;
create policy "cbs writers can insert cbs units"
on public.cbs_units for insert
to authenticated
with check (public.can_write_cbs());

drop policy if exists "cbs writers can update cbs units" on public.cbs_units;
create policy "cbs writers can update cbs units"
on public.cbs_units for update
to authenticated
using (public.can_write_cbs())
with check (public.can_write_cbs());

drop policy if exists "authenticated can read greenhouse units" on public.greenhouse_units;
create policy "authenticated can read greenhouse units"
on public.greenhouse_units for select
to authenticated
using (true);

drop policy if exists "cbs writers can insert greenhouse units" on public.greenhouse_units;
create policy "cbs writers can insert greenhouse units"
on public.greenhouse_units for insert
to authenticated
with check (public.can_write_cbs());

drop policy if exists "cbs writers can update greenhouse units" on public.greenhouse_units;
create policy "cbs writers can update greenhouse units"
on public.greenhouse_units for update
to authenticated
using (public.can_write_cbs())
with check (public.can_write_cbs());

drop policy if exists "authenticated can read inspection history" on public.inspection_history;
create policy "authenticated can read inspection history"
on public.inspection_history for select
to authenticated
using (true);

drop policy if exists "cbs writers can insert inspection history" on public.inspection_history;
create policy "cbs writers can insert inspection history"
on public.inspection_history for insert
to authenticated
with check (public.can_write_cbs());

drop policy if exists "cbs writers can update inspection history" on public.inspection_history;
create policy "cbs writers can update inspection history"
on public.inspection_history for update
to authenticated
using (public.can_write_cbs())
with check (public.can_write_cbs());

commit;
